[providers]
java = "21"

[start]
cmd = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dserver.port=$PORT -Dspring.profiles.active=prod -jar /app/app.jar"

[build]
cmd = "./gradlew clean bootJar -x test"

[variables]
NIXPACKS_JDK_VERSION = "21"