[providers]
java = "21"

[start]
cmd = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dserver.port=$PORT -jar /app/app.jar"

[build]
cmd = "./gradlew clean bootJar -x test"

[variables]
NIXPACKS_JDK_VERSION = "21"